### ISSUE TITLE
Speeding up environment initialization

### ISSUE THREAD

**Issue by Some-random** [lean-dojo/LeanDojo#11]
As I'm running a test program on miniF2F, a runtime bottleneck was observed for LeanDoJo's environment initialization from this operation `with Dojo(theorem) as (dojo, init_state): `, which essentially calls the `"__enter__"` method from DoJo class. The time spent on this initialization was about 10x more than the time spent on neural network inference.

So I tried to parallelize this operation. First by mutli-threading, but I got the following error saying that signal only works in main thread.
```
/bask/projects/j/jlxi8926-auto-sum/dongwei/miniconda/envs/dojo/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.old_sigint = signal.signal(signal.SIGINT, self._exit_gracefully)
  File "/bask/projects/j/jlxi8926-auto-sum/dongwei/miniconda/envs/dojo/lib/python3.10/signal.py", line 56, in signal
    self.run()
ValueError: signal only works in main thread of the main interpreter
    self.old_sigint = signal.signal(signal.SIGINT, self._exit_gracefully)
  File "/bask/projects/j/jlxi8926-auto-sum/dongwei/miniconda/envs/dojo/lib/python3.10/signal.py", line 56, in signal
    self.run()
    self.run()
```

Then I tried multi-processing, which gave me this error message saying there's an object being shared between processes that contains a lock or similar resource.
```
Traceback (most recent call last):
  File "/bask/projects/j/jlxi8926-auto-sum/dongwei/miniconda/envs/dojo/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/bask/projects/j/jlxi8926-auto-sum/dongwei/miniconda/envs/dojo/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/bask/projects/j/jlxi8926-auto-sum/dongwei/LeanDojo/test_interact_multi.py", line 55, in worker
    return_dict[theorem_name] = result
  File "<string>", line 2, in __setitem__
  File "/bask/projects/j/jlxi8926-auto-sum/dongwei/miniconda/envs/dojo/lib/python3.10/multiprocessing/managers.py", line 817, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "/bask/projects/j/jlxi8926-auto-sum/dongwei/miniconda/envs/dojo/lib/python3.10/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/bask/projects/j/jlxi8926-auto-sum/dongwei/miniconda/envs/dojo/lib/python3.10/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: cannot pickle '_thread.lock' object
```

So I'm wondering is there a solution that can speed up the environment initialization?

**Comment by yangky11** [comment]
Do you have an estimate of how long `__enter__` takes?

I'm not sure about how you were trying to use multithreading/multiprocessing. However, it should be possible to use it with multiple processes. Please see [DistributedProver](https://github.com/lean-dojo/ReProver/blob/e8e8777b6296e1696bc8b131d3e55bf9edaa43d2/prover/proof_search.py#L353C4-L353C4).

**Comment by Some-random** [comment]
On my setup, I've found the `__enter__ `method to be a bit time-consuming, averaging around 3 minutes per run. Given that miniF2F comprises over 200 theorems, the overall run time extends quite a bit. I was wondering if your team experienced similar timelines when running experiments on miniF2F?

The multiprocessing code I wrote is pretty standard
```
from lean_dojo import *
import time
import json
from model_inference import inference, init_model
import threading
from multiprocessing import Process, Manager

def init_env(repo_name, commit_id, file_path, repo_type="miniF2F"):
    repo = LeanGitRepo(repo_name, commit_id)
    theorem_list = []
    if repo_type == "miniF2F":
        with open(file_path, "r") as f:
            for line in f.readlines():
                if line.startswith("theorem"):
                    theorem_list.append(line.split()[1])
    return repo, theorem_list

def worker(repo, file_path, theorem_name, return_dict):
    theorem = Theorem(repo, file_path, theorem_name)
    dojo, init_state = Dojo(theorem).__enter__()
    result = (theorem_name, dojo, init_state)
    return_dict[theorem_name] = result


if __name__ == "__main__":
    repo, theorem_list = init_env("https://github.com/openai/miniF2F", "4e433ff5cadff23f9911a2bb5bbab2d351ce5554", "/bask/projects/j/jlxi8926-auto-sum/dongwei/LeanDojo/traced_miniF2F/miniF2F/lean/src/valid.lean", "miniF2F")
    model, tokenizer, generation_config, inference_args = init_model()

    with Manager() as manager:
        # create a shared dictionary to store the results
        return_dict = manager.dict()

        processes = []
        for theorem in theorem_list:
            p = Process(target=worker, args=(repo, "lean/src/valid.lean", theorem, return_dict))
            p.start()
            processes.append(p)

        # Wait for all processes to finish
        for p in processes:
            p.join()

        # convert the shared dict to normal dict for further usage
        results = dict(return_dict)
```

I did attempt to use Ray for multiprocessing following your advice, but unfortunately, I kept stumbling into the same error message. Although I've not delved too deeply into ReProvers code, my understanding is that it may not involve an instance of multiprocessing that calls the __enter__ method. This leads me to believe the situation might not be directly applicable to my case.

**Comment by yangky11** [comment]
3 minutes is definitely possible. There might be some room for improving the initialization time. It wasn't our priority, since the wall time limit for evaluating the prover does not include the time for initialization.

I'm not sure if the `Dojo` object can be passed between different processes. What we did was distributing the testing theorems to different workers. Each worker launches `Dojo`, perform proof search, destroy `Dojo`, and returns the result of proof search.

**Comment by Some-random** [comment]
Thanks for the information! I'm closing this issue for now, will reopen it when/if I have more updates.

**Comment by yangky11** [comment]
Related discussion: https://github.com/lean-dojo/LeanDojo/discussions/50
