### ISSUE TITLE
(Willing to PR) Support async Python

### ISSUE THREAD

**Issue by fzyzcjy** [lean-dojo/LeanDojo#151]
Currently, LeanDojo provides synchronous API. However, it would be great to provide async python API in order to make downstream programming easier.

IMHO this may not be very hard to implement: The `asyncio.subprocess.Process` has quite similar APIs compared with the `subprocess` package LeanDojo is using.

I am willing to PR if this looks ok!

**Comment by yangky11** [comment]
Hi,

Thank you for the suggestion and for offering to help. I'm OK with it as long as it does not break LeanDojo's existing API.
