### ISSUE TITLE
ReProver Warning

### ISSUE THREAD

**Issue by IanWangg** [lean-dojo/LeanDojo#169]
**Description**
I followed the instruction from the ReProver repo, and trying to run the training script. And I get warning like this:
<img width="1478" alt="image" src="https://github.com/lean-dojo/LeanDojo/assets/43913458/19e20164-33a8-40aa-bbd0-21226408ba49">

Should I worry about this? It seems that some lean files are expected from the path "Mathlib/..." and ".lake/...", which I do not have. If this is problematic, how should I fix this?

**Platform Information**
 - OS: Ubuntu 22.04
 - LeanDojo Version [e.g. 1.1.2]

**Comment by yangky11** [comment]
How many warnings did you get? One or two thousands is normal, but a number beyond that may indicate problems.

**Comment by IanWangg** [comment]
A bunch. Thank you for your reply, I think everything's normal. I just want to make sure that my data setup is correct. As I can't find any folders starting from "Mathlib/..." or ".lake/...", and when I ran the trace_repos.py, it returned an empty set.
