### ISSUE TITLE
Alternative function to LeanGitRepo

### ISSUE THREAD

**Issue by LuoKaiGSW** [lean-dojo/LeanDojo#185]
I have a Lean4 project file, but I cannot upload it to Git because it contains company data. Is there any other function similar to LeanGitRepo that allows me to read and track the local git repository? Looking forward to your reply. Thank you!

**Comment by yangky11** [comment]
Is https://github.com/lean-dojo/LeanDojo/pull/179 something you're looking for? I'll review the code and merge it when I get a chance.

**Comment by LuoKaiGSW** [comment]
> Is #179 something you're looking for? I'll review the code and merge it when I get a chance.

Thank you,@yangky11  It works!
