### ISSUE TITLE
Potential bug in tracing theorem which uses "repeat" and "first" tactic

### ISSUE THREAD

**Issue by AG161** [lean-dojo/LeanDojo#19]
Making an issue about a potential bug from this discussion: https://github.com/lean-dojo/LeanDojo/discussions/14

I made a fork of the LeanDojo example repo to test how LeanDojo interacts with certain tactics: https://github.com/AG161/lean4-example
The only change in the fork is adding some simple theorems to Lean4Example.lean.

This is the last theorem I added:

```
theorem dojo4_uncombined (p q r : Prop) (hp : p)
        : (p ∨ q ∨ r) ∧ (q ∨ p ∨ r) ∧ (q ∨ r ∨ p) := by
  repeat (first | apply And.intro | apply Or.inl; assumption | apply Or.inr | assumption)
```

Here the combined tactic continuously goes through the listed tactics until there are no goals left and applies the first one which works, then starts over. For this theorem `get_traced_tactics()` returns:

```
[TracedTactic(tactic=repeat (first | apply And.intro | apply Or.inl; assumption | apply Or.inr | assumption), 
state_before=p q r : Prop
hp : p
⊢ (p ∨ q ∨ r) ∧ (q ∨ p ∨ r) ∧ (q ∨ r ∨ p), state_after=no goals), 

TracedTactic(tactic=(first | apply And.intro | apply Or.inl; assumption | apply Or.inr | assumption), state_before=no goals, state_after=no goals), 

TracedTactic(tactic=first | apply And.intro | apply Or.inl; assumption | apply Or.inr | assumption, state_before=no goals, state_after=no goals), 

TracedTactic(tactic=apply And.intro, state_before=no goals, state_after=no goals), 

TracedTactic(tactic=apply Or.inl, state_before=no goals, state_after=no goals), 

TracedTactic(tactic=assumption, state_before=case right.right.h.h
p q r : Prop
hp : p
⊢ r, state_after=case right.right.h.h
p q r : Prop
hp : p
⊢ r), 

TracedTactic(tactic=apply Or.inr, state_before=no goals, state_after=no goals), 

TracedTactic(tactic=assumption, state_before=no goals, state_after=no goals)]
```
(This is not a direct copy-paste from console, I added some new lines for readability.)

The first tactic in the list looks like what I expected the entire thing to look like - the combined tactic solves the entire goal. However, there are several more tactics that appear in the list which have no goals before and after. At a certain point in the list, it looks like it is tracking which tactics were selected out of the combined tactic (where it says `apply And.intro`), but this only happens for part of the proof and then a lot of the other tactics are left out, and the "no goals" before and after comes back. The output seems like it's wrong to me.

**Comment by yangky11** [comment]
Hi, I checked the`Lean4Example.ast.json` file generated when tracing this repo, somehow each tactic corresponds to multiple (state_before, state_after) pairs. I'll have to take a closer look.

**Comment by yangky11** [comment]
We just released a [new version](https://github.com/lean-dojo/LeanDojo/releases/tag/v1.2.0), which reduces the number of spurious tactics in this issue. However, I don't think a complete fix is coming anytime soon.
