### ISSUE TITLE
Compatibility of Python versions

### ISSUE THREAD

**Issue by samminweng** [lean-dojo/LeanDojo#38]
**Description**
What happened?

The Docker image is using Python 3.11, but LeanDojo requires Python <=3.10

**Detailed Steps to Reproduce the Behavior**
I ran the Dockerfile in the docker folder, which installed Python 3.11. However, when I entered the terminal of the Docker container and used **pip install lean-dojo**, I received the following error messages:

> [root@975563dee4b6 workspace]# pip install lean-dojo
> ERROR: Ignored the following versions that require a different python version: 1.0.0 Requires-Python <3.11,>=3.9; 1.1.0 Requires-Python <3.11,>=3.9; 1.1.1 Requires-Python <3.11,>=3.9; 1.1.2 Requires-Python <3.11,>=3.9; 1.2.0 Requires-Python <3.11,>=3.9
> ERROR: Could not find a version that satisfies the requirement lean-dojo (from versions: none)
> ERROR: No matching distribution found for lean-dojo

Is there any workaround to solve this issue? Thanks. 

![Screenshot 2023-08-15 155344](https://github.com/lean-dojo/LeanDojo/assets/5901362/ab35fb59-3df1-42cf-a913-d495c636f16f)

**Platform Information**
 - OS: Windows
 - Browser [chrome]
 - LeanDojo Version [1.1.2]

**Comment by samminweng** [comment]
Hi @yangky11, 

Thanks for the explanation.
I think the PyCharm project configuration is causing the problem. Would it be helpful to have simple instructions on how to set up LeanDojo with docker? Any suggestion about IDE?

Thanks. 

Here is how I configured the project under PyCharmIDE
(1) Use PyCharm IDE to clone LeanDojo project
(2) Configure the project's interpreter to start the container from Dockerfile inside 'docker' folder'
![image](https://github.com/lean-dojo/LeanDojo/assets/5901362/229412ee-20d0-4cca-9881-f1519933ec3c)

(3) Set the project interpret to use the python inside docker container.   
![image](https://github.com/lean-dojo/LeanDojo/assets/5901362/860a973a-84e9-4495-9679-ed9073bff6f5)

(4) Create example.py file, but the lean-dojo library is missed out
![image](https://github.com/lean-dojo/LeanDojo/assets/5901362/f4f5aba7-6319-4e8b-b84c-980712b647f4)

**Comment by yangky11** [comment]
I have never used PyCharm and thus am unable to help with that. LeanDojo doesn't need any manual setup with Docker. You can just open a terminal and try `docker version`. It's OK as long as it succeeds without errors such as `Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

**Comment by yangky11** [comment]
This could be related to a previous issue with `ray` and `pydantic`: https://github.com/ray-project/ray/issues/37019. I'm not sure if they have fixed the problem. You can try again after making sure both LeanDojo (1.2) and ray (2.6) are their lastest versions. If it doesn't work, maybe try the temporary fix in https://github.com/ray-project/ray/issues/37019.

**Comment by samminweng** [comment]
Hi @yangky11 

The workaround `pip install "pydantic<2"` fixes the issue and tracked lean examples. 
I now have the folder `traced_lean-example` 
Thanks.
