### ISSUE TITLE
Could you trace a single lean file without using github?

### ISSUE THREAD

**Issue by UltimatePea** [lean-dojo/LeanDojo#94]
I see currently Leandojo requires a github repo, is it possible to trace a single file without its dependency locally?

Essentially, I am looking for something that could talk to lean for a single theorem (without any dependency) without much overhead. Thanks!

**Comment by yangky11** [comment]
There are related discussions (https://github.com/lean-dojo/LeanDojo/discussions/78), but currently we do not support this function.

**Comment by UltimatePea** [comment]
Thank you!
